databases:
  - name: postgres
    databaseName: ExpensesTracking_production
    user: ExpensesTracking

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ExpensesTracking_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
