default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ExpensesTracking_development

test:
  <<: *default
  database: ExpensesTracking_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: ExpensesTracking_production
  username: ExpensesTracking
  password: <%= ENV["EXPENSESTRACKING_DATABASE_PASSWORD"] %>
